/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./../components/application-logo.vue')['default']
    Button: typeof import('./../components/button.vue')['default']
    Checkbox: typeof import('./../components/checkbox.vue')['default']
    Dropdown: typeof import('./../components/dropdown.vue')['default']
    DropdownLink: typeof import('./../components/dropdown-link.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    Input: typeof import('./../components/input.vue')['default']
    InputError: typeof import('./../components/input-error.vue')['default']
    Label: typeof import('./../components/label.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    Modal: typeof import('./../components/modal.vue')['default']
    Navbar: typeof import('./../components/navbar.vue')['default']
    NavLink: typeof import('./../components/nav-link.vue')['default']
    ResponsiveNavLink: typeof import('./../components/responsive-nav-link.vue')['default']
  }
}
